Medicines_accounting_system/WebApp/Models/ServicesViewModels/ClinicStatisticsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models.ServicesViewModels
{
    public class ClinicStatisticsViewModel
    {
        public int CountIssuedMedicines { get; set; }
        public int? ClinicId { get; set; }
        public ClinicViewModel Clinic { get; set; }
        public bool HasPreviousPage { get; set; }
        public bool HasNextPage { get; set; }
        public List<PatientViewModel> Patients { get; set; }
        public List<ClinicViewModel> Clinics { get; set; }
        public List<MedicineViewModel> IssuedMedicines { get; set; }

        public ClinicStatisticsViewModel()
        {
            Patients = new List<PatientViewModel>();
            Clinics = new List<ClinicViewModel>();
            IssuedMedicines = new List<MedicineViewModel>();
        }
    }
}

Medicines_accounting_system/WebApp/Models/ServicesViewModels/ClinicViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models.ServicesViewModels
{
    public class ClinicViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public string StatusMessage { get; set; }
    }
}

Medicines_accounting_system/WebApp/Controllers/ClinicController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services;
using WebApp.Models.ServicesViewModels;
using Repository.Models;
using Services.Interfaces;

namespace WebApp.Controllers
{
    public class ClinicController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IClinicsService _clinicsService;
        private readonly IUsersService _usersService;
        private readonly IPatientsService _patientsService;
        private readonly IVisitsService _visitsService;

        [TempData]
        public string StatusMessage { get; set; }

        public ClinicController(
            IMapper mapper, 
            IClinicsService clinicsService, 
            IUsersService usersService, 
            IPatientsService patientsService, 
            IVisitsService visitsService)
        {
            _mapper = mapper;
            _clinicsService = clinicsService;
            _usersService = usersService;
            _patientsService = patientsService;
            _visitsService = visitsService;
        }

        [Authorize(Roles = "sponsor")]
        public IActionResult AddClinic()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "sponsor")]
        public IActionResult AddClinic(ClinicViewModel clinic)
        {
            if (clinic != null && ModelState.IsValid)
            {
                _clinicsService.AddClinic(_mapper.Map<Clinic>(clinic));
                return Content("Clinic successfully added");
            }
            return Content("The data was entered incorrectly");
        }

        [Authorize(Roles = "researcher")]
        public IActionResult AddPatient()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "researcher")]
        public IActionResult AddPatient(PatientViewModel patient)
        {
            if (patient != null && ModelState.IsValid)
            {
                patient.ClinicId = _usersService.GetUserAsync(User).Result.ClinicId;
                if(patient.ClinicId == null)
                {
                    return Content("Error: You are not tied to any of the clinics.");
                }
                patient.Participation = true;
                patient.LastVisit = DateTime.Now;
                if (_patientsService.AddPatient(_mapper.Map<Patient>(patient)))
                {
                    return Content("Patient successfully added");
                }
                return Content("Error: It is impossible to prescribe a medicine to the patient, since the clinic stock is empty");
            }
            return Content("Error: The data was entered incorrectly");
        }

        [Authorize(Roles = "researcher")]
        public IActionResult ViewPatient(int patientId)
        {
            var patient = _patientsService.GetPatientById(patientId);

            var model = _mapper.Map<PatientViewModel>(patient);
            model.Visits = _mapper.Map<List<VisitViewModel>>(_visitsService.GetVisitsByPatient(patientId));
            model.PatientStatuses = _mapper.Map<List<PatientStatusViewModel>>(_patientsService.GetPatientStatuses());
            model.PrescribedMedicine = _mapper.Map<MedicineViewModel>(_clinicsService.GetMedicineById(patient.MedicineId));
            model.StatusMessage = StatusMessage;
            ViewBag.Participation = model.Participation ? "Yes" : "No";

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "researcher")]
        public IActionResult ViewPatient(PatientViewModel model)
        {
            if (ModelState.IsValid)
            {
                _patientsService.UpdatePatientStatus(model.Id, model.PatientStatusId);
                StatusMessage = "Patient status has been updated";
                return PartialView("_StatusMessage", StatusMessage);
            }
            StatusMessage = "Error: The data was entered incorrectly";
            return PartialView("_StatusMessage", StatusMessage);
        }

        [Authorize(Roles = "sponsor, researcher")]
        public IActionResult ClinicStatistics(int page = 1)
        {
            var model = new ClinicStatisticsViewModel
            {
                ClinicId = _usersService.GetUserAsync(User).Result.ClinicId,
                Clinics = _mapper.Map<List<ClinicViewModel>>(_clinicsService.GetClinics())
            };
            if (model.ClinicId != null)
            {
                model.CountIssuedMedicines = _clinicsService.GetCountIssuedMedicinesFromClinic(model.ClinicId);
                model.IssuedMedicines = _mapper.Map<List<MedicineViewModel>>(_clinicsService.GetIssuedMedicinesFromClinic(model.ClinicId));
                model.Clinic = _mapper.Map<ClinicViewModel>(_clinicsService.GetClinicById(model.ClinicId));
                model.Patients = _mapper.Map<List<PatientViewModel>>(_patientsService.TakePatientsFromClinic((int)model.ClinicId, PatientsSortState.NameAsc, page));
                model.HasNextPage = _patientsService.GetHasNextPage();
                model.HasPreviousPage = _patientsService.GetHasPreviousPage();
            }
            ViewData["Page"] = page;
            return View(model);
        }

        [Authorize(Roles = "sponsor, researcher")]
        public IActionResult ClinicStatisticsPartial(ClinicStatisticsViewModel model, int page = 1, PatientsSortState sortState = PatientsSortState.NameAsc)
        {
            ViewData["Page"] = page;
            ViewBag.SortState = sortState;
            ViewBag.Name = sortState == PatientsSortState.NameDesc ? PatientsSortState.NameDesc : PatientsSortState.NameAsc;
            ViewBag.Birthday = sortState == PatientsSortState.BirthdayDesc ? PatientsSortState.BirthdayDesc : PatientsSortState.BirthdayAsc;
            ViewBag.LastVisit = sortState == PatientsSortState.LastVisitDesc ? PatientsSortState.LastVisitDesc : PatientsSortState.LastVisitAsc;
            if (model.ClinicId != null)
            {
                model.CountIssuedMedicines = _clinicsService.GetCountIssuedMedicinesFromClinic(model.ClinicId);
                model.IssuedMedicines = _mapper.Map<List<MedicineViewModel>>(_clinicsService.GetIssuedMedicinesFromClinic(model.ClinicId));
                model.Clinic = _mapper.Map<ClinicViewModel>(_clinicsService.GetClinicById(model.ClinicId));
                model.Patients = _mapper.Map<List<PatientViewModel>>(_patientsService.TakePatientsFromClinic((int)model.ClinicId, sortState, page));
                model.HasNextPage = _patientsService.GetHasNextPage();
                model.HasPreviousPage = _patientsService.GetHasPreviousPage();
            }
            return PartialView(model);
        }

        [Authorize(Roles = "researcher")]
        public IActionResult AddVisit(int patientId)
        {
            var statusMessage = _visitsService.AddVisitByPatient(patientId) ? "Visit has been added" 
                : "Error: Visit hasn't been added: clinic haven't medicines";
            var patient = _patientsService.GetPatientById(patientId);
            var model = _mapper.Map<PatientViewModel>(patient);
            model.PrescribedMedicine = _mapper.Map<MedicineViewModel>(_clinicsService.GetMedicineById(patient.MedicineId));
            model.Visits = _mapper.Map<List<VisitViewModel>>(_visitsService.GetVisitsByPatient(patientId));
            model.PatientStatuses = _mapper.Map<List<PatientStatusViewModel>>(_patientsService.GetPatientStatuses());
            model.StatusMessage = statusMessage;
            ViewBag.Participation = model.Participation ? "Yes" : "No";
            return PartialView("ViewPatientPartial", model);
        }

        [Authorize(Roles = "researcher")]
        public IActionResult EndingParticipation(int patientId)
        {
            _patientsService.EndPatientParticipation(patientId);
            var patient = _patientsService.GetPatientById(patientId);
            var model = _mapper.Map<PatientViewModel>(patient);
            model.PrescribedMedicine = _mapper.Map<MedicineViewModel>(_clinicsService.GetMedicineById(patient.MedicineId));
            model.Visits = _mapper.Map<List<VisitViewModel>>(_visitsService.GetVisitsByPatient(patientId));
            model.PatientStatuses = _mapper.Map<List<PatientStatusViewModel>>(_patientsService.GetPatientStatuses());
            model.StatusMessage = "Patient participation in research has been ended";
            ViewBag.Participation = model.Participation ? "Yes" : "No";
            return PartialView("ViewPatientPartial", model);
        }

        public IActionResult PatientsSort(int clinicId, PatientsSortState sortState = PatientsSortState.NameAsc)
        {
            PatientsSortState newSortState;
            if (sortState == PatientsSortState.NameAsc || sortState == PatientsSortState.NameDesc)
            {
                newSortState = sortState == PatientsSortState.NameAsc ? PatientsSortState.NameDesc : PatientsSortState.NameAsc;
            }
            else
            if (sortState == PatientsSortState.BirthdayAsc || sortState == PatientsSortState.BirthdayDesc)
            {
                newSortState = sortState == PatientsSortState.BirthdayAsc ? PatientsSortState.BirthdayDesc : PatientsSortState.BirthdayAsc;
            }
            else
            {
                newSortState = sortState == PatientsSortState.LastVisitAsc ? PatientsSortState.LastVisitDesc : PatientsSortState.LastVisitAsc;
            }
            return RedirectToAction("ClinicStatisticsPartial", new { clinicId, sortState = newSortState });
        }
    }
}

Medicines_accounting_system/WebApp/Views/Clinic/AddClinic.cshtml
@model WebApp.Models.ServicesViewModels.ClinicViewModel
@{
    ViewData["Title"] = "Adding clinic";
}

<h2>@ViewData["Title"]</h2>

<div class="row" id="clinicForm">
    <div class="col-md-4">
        <form asp-action="AddClinic" method="post"
              data-ajax="true" data-ajax-method="POST" data-ajax-update="#clinicForm">
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-default">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Medicines_accounting_system/WebApp/Views/Clinic/AddPatient.cshtml
@using WebApp.Models.ServicesViewModels
@model PatientViewModel
@{
    ViewData["Title"] = "Adding patient";
}

<h2>@ViewData["Title"]</h2>

<div class="row" id="patientForm">
    <div class="col-md-4">
        <form asp-action="AddPatient" method="post"
              data-ajax="true" data-ajax-method="POST" data-ajax-update="#patientForm">
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday"></label>
                <input type="date" asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender"></label><br />
                <div class="btn-group" data-toggle="buttons">
                    <label asp-for="Gender" class="btn btn-default active">
                        <input asp-for="Gender" type="radio" value="@GenderOfPatient.Male" autocomplete="off" checked> @GenderOfPatient.Male
                    </label>
                    <label asp-for="Gender" class="btn btn-default">
                        <input asp-for="Gender" type="radio" value="@GenderOfPatient.Female" autocomplete="off"> @GenderOfPatient.Female
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-default">Save</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Medicines_accounting_system/WebApp/Views/Clinic/ClinicStatistics.cshtml
@using WebApp.Models.ServicesViewModels
@model ClinicStatisticsViewModel
@{
    ViewData["Title"] = "Cinic statistics";
}

<h3>@ViewData["Title"]</h3><br />

@if (User.IsInRole("researcher"))
{
    <a class="btn btn-primary" asp-action="AddPatient">Add patient</a>
}

@if (User.IsInRole("sponsor"))
{
    <form asp-action="ClinicStatisticsPartial" method="post"
          data-ajax="true" data-ajax-method="GET" data-ajax-update="#listPatients">
        <div>
            <label>Choice of clinic:</label>
            <select asp-for="@Model.ClinicId" class="form-control">
                <option value=""></option>
                @foreach (var clinic in Model.Clinics)
                {
                    <option value="@clinic.Id">@clinic.Name</option>
                }
            </select>
        </div>
        <br />
        <button type="submit" class="btn btn-default">Show</button>
    </form>
}
<br />
<br />
<div id="listPatients">
    @Html.Partial("ClinicStatisticsPartial")
</div>

Medicines_accounting_system/WebApp/Views/Clinic/ClinicStatisticsPartial.cshtml
@using WebApp.Models.ServicesViewModels
@model ClinicStatisticsViewModel

@if (Model.ClinicId != null)
{
    <div id="list">
        <h3>Statistics from clinic @Model.Clinic.Name</h3>
        <br />
        @if (Model.CountIssuedMedicines > 0)
        {
            <h4>
                Issued medicines from clinic:
                @foreach (var medicine in Model.IssuedMedicines.GetRange(0, Model.CountIssuedMedicines - 1).ToList())
                {
                    @medicine.MedicineId@:,
                }
                @Model.IssuedMedicines.Last().MedicineId
            </h4>
        }
        <br/>
        <h4>List of patients from clinic</h4><br />
        <table class="table">
            <tr>
                <th>
                    <a asp-action="PatientsSort" asp-route-clinicId="@Model.ClinicId" asp-route-sortState="@ViewBag.Name"
                       data-ajax="true" data-ajax-method="POST" data-ajax-update="#list">
                        Full name
                    </a>
                </th>
                <th>
                    <a asp-action="PatientsSort" asp-route-clinicId="@Model.ClinicId" asp-route-sortState="@ViewBag.Birthday"
                       data-ajax="true" data-ajax-method="POST" data-ajax-update="#list">
                        Birthday
                    </a>
                </th>
                <th>
                    <a asp-action="PatientsSort" asp-route-clinicId="@Model.ClinicId" asp-route-sortState="@ViewBag.LastVisit"
                       data-ajax="true" data-ajax-method="POST" data-ajax-update="#list">
                        Last visit
                    </a>
                </th>
                <th></th>
            </tr>

            @foreach (var patient in Model.Patients)
            {
                <tr>
                    <td>@patient.FullName</td>
                    <td>@patient.Birthday.ToString("dd.MM.yyyy")</td>
                    <td>@patient.LastVisit</td>
                    @if (User.IsInRole("researcher"))
                    {
                        <td>
                            <a class="btn btn-sm btn-primary" asp-action="ViewPatient" asp-route-patientid="@patient.Id">About</a>
                        </td>
                    }
                </tr>
            }
        </table>

        @if (Model.HasPreviousPage)
        {
            <a asp-action="ClinicStatisticsPartial" asp-route-clinicId="@Model.ClinicId" asp-route-page="@((int) ViewData["Page"] - 1)"
               asp-route-sortState="@ViewBag.SortState"
               data-ajax="true" data-ajax-method="POST" data-ajax-update="#list"
               class="btn btn-default btn">
                <i class="glyphicon glyphicon-chevron-left"></i>
                Back
            </a>
        }
        @if (Model.HasNextPage)
        {
            <a asp-action="ClinicStatisticsPartial" asp-route-clinicId="@Model.ClinicId" asp-route-page="@((int) ViewData["Page"] + 1)"
               asp-route-sortState="@ViewBag.SortState"
               data-ajax="true" data-ajax-method="POST" data-ajax-update="#list"
               class="btn btn-default btn">
                Forward
                <i class="glyphicon glyphicon-chevron-right"></i>
            </a>
        }
    </div>
}

Medicines_accounting_system/WebApp/Views/Clinic/ViewPatient.cshtml
@using WebApp.Models.ServicesViewModels
@model PatientViewModel
@{
    ViewData["Title"] = $"Viewing information about patient {Model.FullName}";
}

<h3>@ViewData["Title"]</h3>

@Html.Partial("ViewPatientPartial", Model)

Medicines_accounting_system/WebApp/Views/Clinic/ViewPatientPartial.cshtml
@using WebApp.Models.ServicesViewModels
@model PatientViewModel

<div id="body">
    <div id="statusMessage">
        @Html.Partial("_StatusMessage", Model.StatusMessage)
    </div>
    <form asp-action="ViewPatient" method="post"
          data-ajax="true" data-ajax-method="POST" data-ajax-update="#statusMessage">
        <input type="hidden" name="Id" value="@Model.Id"/>
        <input type="hidden" name="FullName" value="@Model.FullName"/>
        <input type="hidden" name="Birthday" value="@Model.Birthday"/>
        <input type="hidden" name="Gender" value="@Model.Gender"/>
        <input type="hidden" name="LastVisit" value="@Model.LastVisit"/>
        <dl class="dl-horizontal">
            <dt>Full name:</dt>
            <dd>
                @Model.FullName
            </dd>
            <dt>Birthday:</dt>
            <dd>
                @Model.Birthday.ToString("dd.MM.yyyy")
            </dd>
            <dt>Gender:</dt>
            <dd>
                @Model.Gender
            </dd>
            <dt>Last visit:</dt>
            <dd>
                @Model.LastVisit
            </dd>
            <dt>Number of visits:</dt>
            <dd>
                @Model.Visits.Count
            </dd>
            <dt>Participation:</dt>
            <dd>
                @ViewBag.Participation
            </dd>
            <dt>Prescribed medicine:</dt>
            <dd>
                @Model.PrescribedMedicine.MedicineId
            </dd>
        </dl>
        <h4>Patient visits</h4><br/>
        <table class="table">
            <tr>
                <th>
                    Number
                </th>
                <th>
                    Date
                </th>
                <th></th>
            </tr>
            @foreach (var visit in Model.Visits)
            {
                <tr>
                    <td>@visit.Num</td>
                    <td>@visit.DateOfVisit</td>
                </tr>
            }
        </table>
        <div class="form-group">
            <label asp-for="PatientStatusId">Status</label>
            <select asp-for="PatientStatusId" class="form-control">
                @foreach (PatientStatusViewModel patientStatus in Model.PatientStatuses)
                {
                    <option value="@patientStatus.Id">@patientStatus.Status</option>
                }
            </select>
        </div>
        <div asp-validation-summary="All" class="text-danger"></div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <br/>
    <form asp-action="AddVisit" asp-controller="Clinic" asp-route-patientid="@Model.Id"
          data-ajax="true" data-ajax-method="GET" data-ajax-update="#body">
        @if (Model.Participation)
        {
            <button class="btn btn-primary">Registration of the visit</button>
        }
        else
        {
            <button class="btn btn-primary" disabled>Registration of the visit</button>
        }
    </form>
    <br/>
    <form asp-action="EndingParticipation" asp-controller="Clinic" asp-route-patientid="@Model.Id"
          data-ajax="true" data-ajax-method="GET" data-ajax-update="#body">
        @if (Model.Participation)
        {
            <button class="btn btn-primary">Ending participation in the research</button>
        }
        else
        {
            <button class="btn btn-primary" disabled>Ending participation in the research</button>
        }
    </form>
</div>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}