Medicines_accounting_system/WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Repository.Models;
using Services.Interfaces;
using WebApp.Extensions;
using WebApp.Models.AdminViewModels;
using WebApp.Models.ServicesViewModels;

namespace WebApp.Controllers
{
    [Authorize(Roles = "sponsor, researcher")]
    public class AdminController : Controller
    {
        private readonly IEmailSender _emailSender;
        private readonly IUsersService _usersService;
        private readonly IClinicsService _clinicsService;
        private readonly IMapper _mapper;

        [TempData]
        public string StatusMessage { get; set; }

        public AdminController(IEmailSender emailSender, IUsersService usersService, 
            IClinicsService clinicsService, IMapper mapper)
        {
            _emailSender = emailSender;
            _usersService = usersService;
            _clinicsService = clinicsService;
            _mapper = mapper;
        }

        public IActionResult Index(int page = 1)
        {
            var model = new UsersViewModel
            {
                Users = _mapper.Map<List<UserViewModel>>(_usersService.TakeUsers(page)),
                HasPreviousPage = _usersService.GetHasPreviousPage(),
                HasNextPage = _usersService.GetHasNextPage()
            };
            ViewData["Page"] = page;
            return View(model);
        }

        public IActionResult IndexPartial(int page = 1)
        {
            var model = new UsersViewModel
            {
                Users = _mapper.Map<List<UserViewModel>>(_usersService.TakeUsers(page)),
                HasPreviousPage = _usersService.GetHasPreviousPage(),
                HasNextPage = _usersService.GetHasNextPage(),
                StatusMessage = StatusMessage
            };
            ViewData["Page"] = page;
            return PartialView(model);
        }

        [Authorize(Roles = "sponsor")]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _usersService.GetUserByIdAsync(userId);
            var userRoles = await _usersService.GetUserRoles(user);
            var allRoles = _usersService.GetRoles();
            var clinics = _mapper.Map<List<ClinicViewModel>>(_clinicsService.GetClinics());
            var model = _mapper.Map<ChangeUserViewModel>(user);
            model.AllRoles = allRoles;
            model.UserRoles = userRoles;
            model.Clinics = clinics;

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "sponsor")]
        public async Task<IActionResult> EditPartial(ChangeUserViewModel model)
        {
            var clinics = _mapper.Map<List<ClinicViewModel>>(_clinicsService.GetClinics());
            model.AllRoles = _usersService.GetRoles();
            model.Clinics = clinics;
            if (ModelState.IsValid)
            {
                var user = await _usersService.GetUserByIdAsync(model.Id);
                var userUpdate = _mapper.Map<User>(model);
                userUpdate.Blocked = user.Blocked;
                userUpdate.BlockingReason = user.BlockingReason;
                userUpdate.DatePasswordSet = user.DatePasswordSet;
                var result = await _usersService.UpdateUserById(model.Id, userUpdate, model.UserRoles);
                if (result.Succeeded)
                {
                    model.StatusMessage = "User profile has been updated";
                    return PartialView(model);
                }
                AddErrors(result);
            }
            return PartialView(model);
        }

        [Authorize(Roles = "sponsor")]
        public async Task<IActionResult> Block(string userId)
        {
            var user = await _usersService.GetUserByIdAsync(userId);
            var model = _mapper.Map<BlockUserViewModel>(user);
            model.StatusMessage = StatusMessage;

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "sponsor")]
        public async Task<IActionResult> BlockPartial(BlockUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _usersService.BlockUser(model.Id, model.BlockingReason);
                if (result.Succeeded)
                {
                    model.Blocked = true;
                    model.StatusMessage = "User has been blocked";
                    return PartialView(model);
                }
                AddErrors(result);
            }

            return PartialView(model);
        }

        [Authorize(Roles = "sponsor")]
        public async Task<IActionResult> Unblock(string userId, int page = 1)
        {
            var result = await _usersService.UnblockUser(userId);
            if (result.Succeeded)
            {
                StatusMessage = "User has been unblocked";
                return RedirectToAction("IndexPartial", new {page});
            }
            StatusMessage = "Error: user not found";
            return RedirectToAction("IndexPartial", new { page });
        }

        [Authorize(Roles = "sponsor")]
        public async Task<IActionResult> ResetPassword(string userId)
        {
            var user = await _usersService.GetUserByIdAsync(userId);
            var code = await _usersService.GetPasswordResetTokenAsync(user);
            var callbackUrl = Url.ResetPasswordCallbackLink(user.Id, code, Request.Scheme);
            await _emailSender.SendEmailAsync(user.Email, "Reset Password",
                $"The research sponsor reset your password. Please reset your password by clicking here: <a href='{callbackUrl}'>link</a>");
            StatusMessage = "User password has been reseted";
            return PartialView("_StatusMessage", StatusMessage);
        }

        [Authorize(Roles = "researcher")]
        public async Task<IActionResult> ViewUser(string userId)
        {
            var user = await _usersService.GetUserByIdAsync(userId);
            var userRoles = await _usersService.GetUserRoles(user);
            var model = _mapper.Map<UserViewModel>(user);
            var clinic = _mapper.Map<ClinicViewModel>(_clinicsService.GetClinicById(user.ClinicId));
            model.UserRoles = userRoles;
            model.Clinic = clinic;

            return View(model);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
    }
}

Medicines_accounting_system/WebApp/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Services;
using WebApp.Models.ServicesViewModels;
using Repository.Models;
using Services.Interfaces;

namespace WebApp.Controllers
{
    public class StockController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IClinicsService _clinicsService;
        private readonly IStockService _stockService;
        private readonly IHostingEnvironment _hostingEnvironment;

        [TempData]
        public string StatusMessage { get; set; }

        public StockController(IMapper mapper, 
            IClinicsService clinicsService, 
            IStockService stockService,
            IHostingEnvironment hostingEnvironment)
        {
            _mapper = mapper;
            _clinicsService = clinicsService;
            _stockService = stockService;
            _hostingEnvironment = hostingEnvironment;
        }
        
        [Authorize(Roles = "manager")]
        public IActionResult AddMedicineToStock()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public IActionResult AddMedicineToStock(MedicineViewModel medicine)
        {
            if (medicine != null && ModelState.IsValid)
            {
                _stockService.AddMedicine(_mapper.Map<Medicine>(medicine));
                return Content("Medicine successfully added to stock");
            }
            return Content("The data was entered incorrectly");
        }

        [Authorize(Roles = "manager")]
        public IActionResult EditMedicineOnStock(int medicineId)
        {
            var medicine = _stockService.GetMedicineFromStock(medicineId);

            var model = _mapper.Map<MedicineViewModel>(medicine);
            model.StatusMessage = StatusMessage;

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public IActionResult EditMedicineOnStock(MedicineViewModel model)
        {
            if (ModelState.IsValid)
            {
                var medicineUpdate = _mapper.Map<Medicine>(model);
                _stockService.UpdateMedicineOnStock(model.Id, medicineUpdate);
                StatusMessage = "Medicine data has been updated";
                return PartialView("_StatusMessage", StatusMessage);
            }
            StatusMessage = "Error: The data was entered incorrectly:<br>";
            var allErrors = ModelState.Values.SelectMany(v => v.Errors.Select(b => b.ErrorMessage));
            foreach (var error in allErrors)
            {
                StatusMessage += $"{error}<br>";
            }
            return PartialView("_StatusMessage", StatusMessage);
        }

        [Authorize(Roles = "manager")]
        public IActionResult SendMedicineToClinic()
        {
            var model = new SentMedicineView
            {
                Clinics = _mapper.Map<List<ClinicViewModel>>(_clinicsService.GetClinics()),
                Medicines = _mapper.Map<List<MedicineViewModel>>(_stockService.GetMedicinesFromStock()),
                StatusMessage = StatusMessage
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "manager")]
        public IActionResult SendMedicineToClinic(SentMedicineView model)
        {
            if (model != null && ModelState.IsValid)
            {
                var sentResult = _stockService.SendMedicine(model.MedicineId, model.Count);
                if (sentResult)
                {
                    _clinicsService.AddMedicineToClinic(model.ClinicId, model.MedicineId, model.Count);
                    StatusMessage = "Medicines were successfully sent out";
                    return PartialView("_StatusMessage", StatusMessage);
                }
                StatusMessage = "Error: Not enough medicine in the stock";
                return PartialView("_StatusMessage", StatusMessage);
            }
            StatusMessage = "Error: The form was entered incorrectly";
            return PartialView("_StatusMessage", StatusMessage);
        }

        [Authorize(Roles = "manager")]
        public IActionResult AutoSendMedicines()
        {
            var sentResult = _stockService.AutomaticSendMedicinesToClinic();
            if (sentResult != null)
            {
                var totalCount = sentResult.Sum(s => s.Count);
                if (totalCount == 0)
                {
                    StatusMessage = "Error: In the clinics a sufficient supply of medicines";
                    return PartialView("_StatusMessage", StatusMessage);
                }
                StatusMessage = "Medicines were successfully sent out:<br/>";
                foreach (var storage in sentResult)
                {
                    if(storage.Count > 0)
                    {
                        var clinic = _clinicsService.GetClinicById(storage.ClinicId);
                        StatusMessage += $"Medicine with ID {storage.Medicine.MedicineId} in amount {storage.Count} to the {clinic.Name} clinic<br/>";
                    }
                }
                return PartialView("_StatusMessage", StatusMessage);
            }
            StatusMessage = "Error: Not enough medicines in the stock";
            return PartialView("_StatusMessage", StatusMessage);
        }

        [Authorize(Roles = "manager")]
        public ActionResult SendMedicinesFromExcelTable()
        {
            IFormFile file = Request.Form.Files[0];
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }

            if (_stockService.SendMedicinesFromExcelTable(file, newPath))
            {
                StatusMessage = "Medicines were successfully sent out";
                return RedirectToAction("SendMedicineToClinic");
            }
            StatusMessage = "Error: Error adding medicines";
            return RedirectToAction("SendMedicineToClinic");
        }

        [Authorize(Roles = "sponsor, manager")]
        public IActionResult StockManagement(int page = 1)
        {
            ViewData["Page"] = page;
            ViewBag.SortState = StockSortState.IdAsc;
            return View(_stockService);
        }

        [Authorize(Roles = "sponsor, manager")]
        public IActionResult StockManagementPartial(int page = 1, StockSortState sortState = StockSortState.IdAsc)
        {
            ViewData["Page"] = page;
            ViewBag.SortState = sortState;
            ViewBag.Id = sortState == StockSortState.IdDesc ? StockSortState.IdDesc : StockSortState.IdAsc;
            ViewBag.Form = sortState == StockSortState.FormDesc ? StockSortState.FormDesc : StockSortState.FormAsc;
            ViewBag.Container = sortState == StockSortState.ContainerDesc ? StockSortState.ContainerDesc : StockSortState.ContainerAsc;
            ViewBag.Number = sortState == StockSortState.NumOfStockDesc ? StockSortState.NumOfStockDesc : StockSortState.NumOfStockAsc;
            ViewBag.ExpirationDate = sortState == StockSortState.ExpirationDateOfMedicineDesc ? StockSortState.ExpirationDateOfMedicineDesc : StockSortState.ExpirationDateOfMedicineAsc;
            return PartialView(_stockService);
        }

        [Authorize(Roles = "manager")]
        public IActionResult DeleteMedicine(int medicineId)
        {
            _stockService.DeleteMedicineFromStock(medicineId);
            return RedirectToAction("StockManagementPartial");
        }
        
        public IActionResult StockSort(StockSortState sortState = StockSortState.IdAsc)
        {
            StockSortState newSortState;
            if (sortState == StockSortState.IdAsc || sortState == StockSortState.IdDesc)
            {
                newSortState = sortState == StockSortState.IdAsc ? StockSortState.IdDesc : StockSortState.IdAsc;
            }
            else
            if (sortState == StockSortState.FormAsc || sortState == StockSortState.FormDesc)
            {
                newSortState = sortState == StockSortState.FormAsc ? StockSortState.FormDesc : StockSortState.FormAsc;
            }
            else
            if (sortState == StockSortState.ContainerAsc || sortState == StockSortState.ContainerDesc)
            {
                newSortState = sortState == StockSortState.ContainerAsc ? StockSortState.ContainerDesc : StockSortState.ContainerAsc;
            }
            else
            if (sortState == StockSortState.NumOfStockAsc || sortState == StockSortState.NumOfStockDesc)
            {
                newSortState = sortState == StockSortState.NumOfStockAsc ? StockSortState.NumOfStockDesc : StockSortState.NumOfStockAsc;
            }
            else
            {
                newSortState = sortState == StockSortState.ExpirationDateOfMedicineAsc ? StockSortState.ExpirationDateOfMedicineDesc : StockSortState.ExpirationDateOfMedicineAsc;
            }
            return RedirectToAction("StockManagementPartial", new { sortState = newSortState });
        }

        public async Task<IActionResult> ExportStockToExcel()
        {
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string sFileName = $@"stock_{DateTime.Now:dd_MM_yyyy}.xlsx";
            var memory = await _stockService.ExportMedicinesToExcel(sWebRootFolder, sFileName);
            return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sFileName);
        }
    }
}

Medicines_accounting_system/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Medicines accounting system</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav id="menu" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if(User.IsInRole("sponsor")|| User.IsInRole("researcher"))
                    {
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">User management panel</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" role="button" data-toggle="dropdown">
                                Statistics <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Home" asp-action="ResearchStatistics">Research statistics</a></li>
                                <li><a asp-controller="Clinic" asp-action="ClinicStatistics">Clinic statistics</a></li>
                            </ul>
                        </li>
                    }
                    @if(User.IsInRole("sponsor"))
                    {
                        <li><a asp-area="" asp-controller="Clinic" asp-action="AddClinic">Add clinic</a></li>
                    }
                    @if(User.IsInRole("sponsor")|| User.IsInRole("manager"))
                    {
                        <li><a asp-area="" asp-controller="Stock" asp-action="StockManagement">Stock management</a></li>
                    }
                    @if(User.IsInRole("manager"))
                    {
                        <li><a asp-area="" asp-controller="Stock" asp-action="SendMedicineToClinic">Delivery of medicines to clinic</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Medicines accounting system</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Medicines_accounting_system/WebApp/Views/Shared/_StatusMessage.cshtml
@using System.Web
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Html.Raw(HttpUtility.HtmlDecode(Model))
    </div>
}